✨ Use ticker title and description for signal group details
systemli/ticker pull request #328
Opened 2024-07-05 12:49 UTC by doobry-systemli

2024-07-06 15:51 UTC, 0x46616c6b requested changes

2024-07-06 15:51 UTC, 0x46616c6b commented on internal/bridge/bridge.go
> +	UpdateTicker(ticker storage.Ticker) error
```suggestion
	Update(ticker storage.Ticker) error
```

I would only call it Update.

2024-07-07 09:54 UTC, doobry-systemli commented on internal/bridge/bridge.go
> +	UpdateTicker(ticker storage.Ticker) error
This is changed now.

2024-07-07 14:53 UTC, 0x46616c6b approved these changes

2024-07-07 15:11 UTC, merged